# scripts/generate_all_cnot_round_patterns.py

import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from src.config import (
    DATA_DIR,
    DEFAULT_N_ROUNDS,
    DEFAULT_ERROR_TYPES,
    DEFAULT_INCLUDE_EMPTY,
    DEFAULT_SITUATIONS,
)
from src.dataset_generators import (
    generate_fixed_cnot_round_pattern_rows,
    situation_name,
)
from src.io_utils import save_csv, save_metadata
from src.simulator import make_repeated_stabilizer_qnode
from src.surface_code_layout import enumerate_stabilizer_cnots


def parse_error_types(error_types_str):
    """
    Examples:
        "XZ"   -> ("X", "Z")
        "X,Z"  -> ("X", "Z")
    """

    if "," in error_types_str:
        parts = error_types_str.split(",")
    else:
        parts = list(error_types_str)

    parts = tuple(p.strip().upper() for p in parts if p.strip())

    if len(parts) != 2:
        raise ValueError(
            f"error_types must contain two Pauli types. Got: {error_types_str}"
        )

    for p in parts:
        if p not in {"X", "Y", "Z"}:
            raise ValueError(f"Invalid Pauli type: {p}")

    return parts


def build_arg_parser():
    parser = argparse.ArgumentParser(
        description=(
            "Generate datasets for all directed CNOT locations and all "
            "round-wise fault occurrence patterns."
        )
    )

    parser.add_argument(
        "--n-rounds",
        type=int,
        default=DEFAULT_N_ROUNDS,
        help=f"Number of stabilizer rounds. Default: {DEFAULT_N_ROUNDS}",
    )

    parser.add_argument(
        "--error-types",
        type=str,
        default="".join(DEFAULT_ERROR_TYPES),
        help='Pauli errors, e.g. "XZ" or "X,Z". Default: XZ',
    )

    parser.add_argument(
        "--include-empty",
        action="store_true",
        default=DEFAULT_INCLUDE_EMPTY,
        help="Include the no-fault pattern. Default follows config.py.",
    )

    parser.add_argument(
        "--exclude-empty",
        action="store_true",
        help="Exclude the no-fault pattern.",
    )

    parser.add_argument(
        "--mode",
        type=str,
        default="all",
        choices=[
            "all",
            "mid_reset",
            "mid_no_reset",
            "no_mid_sample",
            "no_mid_probs",
        ],
        help="Which simulation mode to run. Default: all",
    )

    parser.add_argument(
        "--output-root",
        type=str,
        default=str(DATA_DIR),
        help=f"Output root directory. Default: {DATA_DIR}",
    )

    parser.add_argument(
        "--one-file",
        action="store_true",
        help=(
            "Save all CNOT locations into one CSV file per mode. "
            "If not set, save one CSV file per CNOT location."
        ),
    )

    return parser


def select_situations(mode):
    if mode == "all":
        return DEFAULT_SITUATIONS

    mapping = {
        "mid_reset": {
            "mid_measure": True,
            "reset_after_measure": True,
            "return_probs": False,
            "shots": 1,
        },
        "mid_no_reset": {
            "mid_measure": True,
            "reset_after_measure": False,
            "return_probs": False,
            "shots": 1,
        },
        "no_mid_sample": {
            "mid_measure": False,
            "reset_after_measure": False,
            "return_probs": False,
            "shots": 1,
        },
        "no_mid_probs": {
            "mid_measure": False,
            "reset_after_measure": False,
            "return_probs": True,
            "shots": None,
        },
    }

    return [mapping[mode]]


def add_cnot_metadata(rows, cnot_index, loc):
    """
    Add CNOT-location metadata to rows generated by
    generate_fixed_cnot_round_pattern_rows.
    """

    for row in rows:
        row["dataset_type"] = "all_cnot_round_patterns"
        row["cnot_index"] = int(cnot_index)
        row["stab_type"] = loc["stab_type"]
        row["stab_index"] = int(loc["stab_index"])

    return rows


def main():
    parser = build_arg_parser()
    args = parser.parse_args()

    n_rounds = args.n_rounds
    error_types = parse_error_types(args.error_types)
    include_empty = args.include_empty and not args.exclude_empty
    output_root = Path(args.output_root)
    situations = select_situations(args.mode)

    cnot_locations = enumerate_stabilizer_cnots()

    for situation in situations:
        shots = situation["shots"]

        qnode = make_repeated_stabilizer_qnode(
            n_rounds=n_rounds,
            shots=shots,
            mid_measure=situation["mid_measure"],
            reset_after_measure=situation["reset_after_measure"],
            return_probs=situation["return_probs"],
        )

        mode_name = situation_name(
            mid_measure=situation["mid_measure"],
            reset_after_measure=situation["reset_after_measure"],
            return_probs=situation["return_probs"],
        )

        output_dir = output_root / mode_name

        all_rows = []

        for cnot_index, loc in enumerate(cnot_locations):
            control = loc["control"]
            target = loc["target"]

            rows = generate_fixed_cnot_round_pattern_rows(
                qnode=qnode,
                n_rounds=n_rounds,
                shots=shots,
                control=control,
                target=target,
                error_types=error_types,
                include_empty=include_empty,
                mid_measure=situation["mid_measure"],
                reset_after_measure=situation["reset_after_measure"],
                return_probs=situation["return_probs"],
            )

            rows = add_cnot_metadata(
                rows=rows,
                cnot_index=cnot_index,
                loc=loc,
            )

            if args.one_file:
                all_rows.extend(rows)
            else:
                filename = (
                    f"cnot_{cnot_index:02d}_"
                    f"{control}_{target}_"
                    f"{''.join(error_types)}_"
                    f"rounds_{n_rounds}_all_patterns.csv"
                )

                output_path = output_dir / "all_cnot_round_patterns" / filename
                save_csv(rows, output_path)

                print(f"Saved: {output_path}")
                print(f"Rows: {len(rows)}")

        if args.one_file:
            filename = (
                f"all_cnots_"
                f"{''.join(error_types)}_"
                f"rounds_{n_rounds}_all_patterns.csv"
            )

            output_path = output_dir / filename
            save_csv(all_rows, output_path)

            print(f"Saved: {output_path}")
            print(f"Rows: {len(all_rows)}")

        num_patterns_per_cnot = 2 ** n_rounds if include_empty else 2 ** n_rounds - 1

        metadata_path = (
            output_dir
            / f"metadata_all_cnots_{''.join(error_types)}_rounds_{n_rounds}_all_patterns.json"
        )

        save_metadata(
            {
                "dataset_type": "all_cnot_round_patterns",
                "mode": mode_name,
                "n_rounds": n_rounds,
                "shots": shots,
                "error_types": list(error_types),
                "include_empty": include_empty,
                "num_cnot_locations": len(cnot_locations),
                "num_patterns_per_cnot": num_patterns_per_cnot,
                "expected_num_samples": len(cnot_locations) * num_patterns_per_cnot,
                "saved_as_one_file": bool(args.one_file),
                "cnot_locations": cnot_locations,
                **situation,
            },
            metadata_path,
        )

        print(f"Saved metadata: {metadata_path}")


if __name__ == "__main__":
    main()